### ISSUE TITLE
大佬能不能 做下那个时间响应的排序

### ISSUE THREAD

**Issue by liquO0o** [Ernket/xia_sql_modify#1]

**Comment by Ernket** [comment]
有时间的话看看，因为我现在改的其实也很多bug，没啥信心改好，那个排序有时候也没反应，得先点payload再点返回包长度排序

**Comment by Ernket** [comment]
更新了，有空可以试试，有任何报错欢迎师傅反馈

https://github.com/Ernket/xia_sql_modify/releases/tag/3.3.3
